### ISSUE TITLE
Question about Texture Packs

### ISSUE THREAD

**Issue by korbosoft** [UnderVolt/Moon64#1]
Just a Question, how do i create a texture pack?

i can upload my attempt at one, if it helps.

 - OS: PC
 - Version: IDK, how do i find it?

it was a .bit file. but i renamed it to zip so i could upload it.

**Comment by TheBauti** [comment]
you have to create a zip file and put the textures you want into a folder named "gfx". to put the texture pack in game, the directory is /youreponame/build/us_pc/res.
